### PR TITLE
added discord server to readme.md

### PR DESCRIPTION
**Pull request by TrainzMarcel**

### CODE REVIEW

**Comment by gilzoide** [comment]
Thanks for the addition.
To be honest, I like better these badges at the top, just after the title. Just like [Shield.io's own repo README](https://github.com/badges/shields), although I see no need to have them centralized.
If we add more badges, they all live in the same place and we cut the explanation texts, since these badges are quite self-explanatory. Now that I'm thinking of it, a badge linking to the Godot Asset Library would be a nice addition, I'll add it later.
What do you think?

**Comment by TrainzMarcel** [comment]
good idea! i myself didnt know where to put the discord badge and i thought it looked out of place there without an explanation. feel free to move it around however u like

**Comment by gilzoide** [comment]
> feel free to move it around however u like and remove the explanation

I'm not merging your PR only to change everything you added right after.
Change it in your branch, then I'll merge it in the right place and your name will be kept in the blame ^^

**Comment by TrainzMarcel** [comment]
sorry that took so long, i had a busy week

**Review by gilzoide — APPROVED** [review]

**Comment by gilzoide** [comment]
Don't worry about that, I know how that goes.
I think it's better now, at the top of the README, thanks for the contribution!

**Pull request merged**
